name: Create Release Pull Requests
on:
  push:
    branches:
      - '**'

jobs:
  create-main-pr:
    name: Create Release PR Against main
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "RELEASE -> 'main' +semver: minor"
          labels: 'release'
          base: main
          branch: ${{ github.ref }}

  create-develop-pr:
    name: Create Release PR Against develop
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "RELEASE -> 'develop'"
          labels: 'release'
          base: develop
          branch: ${{ github.ref }}
